spring:
  application:
    name: task-manager-api

  datasource:
    url: jdbc:postgresql://localhost:5433/bd_tareas_usuarios
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none





